# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-yaml
        name: Check YAML files
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=500']
      - id: check-json
        name: Check JSON files
      - id: check-toml
        name: Check TOML files
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-case-conflict
        name: Check for case conflicts
      - id: mixed-line-ending
        name: Check mixed line endings
      - id: detect-private-key
        name: Detect private keys

  # Python linting and formatting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        name: Lint with Ruff
        args: ['--fix', '--exit-non-zero-on-fix']
      - id: ruff-format
        name: Format with Ruff

  # Run tests
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: bash -c 'source .venv/bin/activate && pytest tests/ -x --tb=short -q'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

# Configuration for specific hooks
default_language_version:
  python: python3

# Files to exclude from all hooks
exclude: |
  (?x)^(
    \.venv/|
    venv/|
    build/|
    dist/|
    .*\.egg-info/|
    __pycache__/|
    \.pytest_cache/|
    \.mypy_cache/|
    \.git/|
    \.github/
  )$
